web/src/components/table/table_controls.scss
web/src/components/timeIntervalSelect/TimeIntervalSelect.tsx
web/src/components/timeIntervalSelect/interval_select.scss

[Notion Task](https://www.notion.so/lncapital/Arrows-to-quickly-jump-timeframes-33ccbaab3d8c404aab0c1335a6cfd59b)
https://user-images.githubusercontent.com/1019869/162409628-800a0c7a-5843-4702-bc9e-874730f40f97.mp4

Add time travel arrows

---

go.mod
go.sum
internal/logging/logging.go
internal/logging/logging_test.go

Add logging to project using zerolog package

Add logging package to project

---

internal/invoices/handlers.go
internal/invoices/new_invoice.go
internal/invoices/new_invoice_test.go

POST method
input fields:
memo: string - optional
valueMsat: int - mandatory
expiry: int - optional. default 3600
amp: bool - optional. default false

create new invoice endpoint: api/invoices/newinvoice

---

web/package-lock.json
web/package.json
web/src/index.tsx

This fixes the entry point to utilize the new render API

React18 render upgrade

---

web/src/App.tsx
web/src/RequireAuth.tsx
web/src/Router.tsx
web/src/constants/routes.ts
web/src/features/settings/NodeSettings.module.scss
web/src/features/templates/templates.module.scss

This is a proposal for a better router component, by using a declarative routing layout and centralizing the routes definitions under a single file

Router refactor

---

web/src/App.tsx
web/src/Router.tsx
web/src/constants/routes.ts
web/src/features/channel/DashboardPage.tsx
web/src/features/navigation/MenuItem.tsx
web/src/features/transact/Payments/PaymentsPage.tsx
web/src/features/transact/Payments/newPayment/NewPaymentModal.tsx
web/src/index.tsx

This update allows modals to pop up by changing the current to location to its route. It's going to be useful for performing certain actions without changing the page, but still updating the router location

Display modals from routes

---

web/src/App.test.tsx

The testing library has been upgraded and exposed a new version of the API. This PR fixes the test case for the login page render.

Update page render test case

---

internal/channel_history/channel_balance.go

Multipart payments is not correctly included in channel balance.

---

cmd/torq/internal/torqsrv/server.go
database/migrations/000041_add_language_to_settings.down.psql
database/migrations/000041_add_language_to_settings.up.psql
internal/settings/database.go
internal/settings/routes.go
web/package-lock.json
web/package.json
web/public/locales/en.json
web/public/locales/nl.json
web/src/App.test.tsx
web/src/App.tsx
web/src/apiTypes.ts
web/src/config/i18nConfig.js
web/src/features/settings/SettingsPage.tsx
web/src/services/i18n/i18nAPI.js
web/src/services/i18n/i18nSlice.js
web/src/services/i18n/useTranslations.js
web/src/store/store.ts

Add support for other languages.

#92: Add support for other languages.

---

cmd/torq/internal/subscribe/server.go
cmd/torq/internal/torqsrv/server.go
cmd/torq/internal/torqsrv/websocket.go
cmd/torq/torq.go
pkg/lnd/channel_events.go
pkg/lnd/channel_events_test.go
pkg/lnd/invoices.go
pkg/lnd/peer_events.go
pkg/lnd/transactions.go

send subscribe events(channel, invoice, peer, transaction) to websocket channel

send subscribe events to websocket

---

test/e2e/lnd/e2e_test.go

Playwright is incorrectly waiting for Default view on channels page

---

cmd/torq/internal/torqsrv/server.go
cmd/torq/internal/torqsrv/websocket.go
internal/on_chain_tx/new_address.go
internal/payments/new_payment.go
web/src/features/transact/OnChain/OnChainPage.tsx
web/src/features/transact/Payments/newPayment/NewPaymentModal.tsx
web/src/features/transact/Payments/newPayment/newPayments.module.scss

Websocket close error

---

web/src/features/channels/ChannelsSlice.tsx
web/src/features/sidebar/sections/columns/ColumnsSection.tsx
web/src/features/sidebar/sections/sort/SortSection.tsx
web/src/features/transact/OnChain/OnChainPage.tsx
web/src/utils/UseStrictDroppable.tsx

Fixes #159 
In this commit there are a lot of indentation fixes that I believe is caused by prettier, however I'm not sure if these are the correct setup. Did we add new prettier rules? If not I'll update these with the correct prettier settings.

Fix drag & drop bug related to react 18 upgrade

---

cmd/torq/internal/torqsrv/websocket.go
internal/invoices/decode_invoice.go
internal/invoices/handlers.go
internal/invoices/new_invoice.go
internal/invoices/new_invoice_test.go
internal/on_chain_tx/handlers.go
internal/on_chain_tx/new_address.go
internal/on_chain_tx/send_coins.go
internal/on_chain_tx/send_coins_test.go
internal/payments/new_payment.go
internal/payments/new_payment_test.go
internal/settings/node_connection_details.go
web/src/apiSlice.ts
web/src/features/forms/TextInput.tsx
web/src/features/settings/SettingsPage.tsx
web/src/features/templates/popoutPageTemplate/PopoutPageTemplate.tsx
web/src/features/toast/toast.module.css
web/src/features/transact/OnChain/newAddress/NewAddressModal.tsx
web/src/features/transact/Payments/PaymentsPage.tsx
web/src/features/transact/Payments/newPayment/InvoicePayment.tsx
web/src/features/transact/Payments/newPayment/InvoicePaymentResponse.tsx
web/src/features/transact/Payments/newPayment/NewPaymentModal.tsx
web/src/features/transact/Payments/newPayment/OnChainPaymentResponse.tsx
web/src/features/transact/Payments/newPayment/OnChanPaymentDetails.tsx
web/src/features/transact/Payments/newPayment/newPayments.module.scss
web/src/features/transact/Payments/newPayment/types.ts
web/src/features/transact/Payments/paymentTypes.ts
web/src/types/api.ts

* On-Chain payments supported
* Improved UI for onchain and LN payment responses
Closes #108

On-Chain payments and improved Payment response UI

---

cmd/torq/internal/torqsrv/server.go
internal/channels/open_channel.go
internal/peers/connect_peer.go
internal/peers/connect_peer_test.go
internal/peers/handlers.go
internal/peers/list_peers.go

connect peer & list peers endpoints
connect peer when opening channel

connect peer & list peers

---

cmd/torq/internal/torqsrv/websocket.go
internal/invoices/handlers.go
internal/invoices/new_invoice.go
web/public/locales/en.json
web/src/Router.tsx
web/src/apiSlice.ts
web/src/constants/routes.ts
web/src/features/inputs/largeAmountInput/LargeAmountInput.tsx
web/src/features/inputs/largeAmountInput/largeAmountInput.module.scss
web/src/features/note/Note.tsx
web/src/features/note/note.module.scss
web/src/features/progressTabs/progressHeader.module.scss
web/src/features/progressTabs/progressTabs.module.scss
web/src/features/templates/popoutPageTemplate/popoutDetails/PopoutDetails.tsx
web/src/features/templates/popoutPageTemplate/popoutDetails/StatusIcon.tsx
web/src/features/templates/popoutPageTemplate/popoutDetails/popoutDetails.module.scss
web/src/features/templates/popoutPageTemplate/popoutDetails/statusIcon.module.scss
web/src/features/templates/popoutPageTemplate/popoutPageTemplate.module.scss
web/src/features/transact/Invoices/InvoicesPage.tsx
web/src/features/transact/Invoices/newInvoice/NewInvoiceModal.tsx
web/src/features/transact/Invoices/newInvoice/newInvoice.module.scss
web/src/features/transact/Invoices/newInvoice/newInvoiceResponse.tsx
web/src/features/transact/Invoices/newInvoice/newInvoiceTypes.ts
web/src/features/transact/OnChain/newAddress/NewAddressModal.tsx
web/src/features/transact/Payments/PaymentsPage.tsx
web/src/features/transact/Payments/newPayment/InvoicePaymentResponse.tsx
web/src/features/transact/Payments/newPayment/NewPaymentModal.tsx
web/src/features/transact/Payments/newPayment/OnChainPaymentResponse.tsx
web/src/features/transact/Payments/newPayment/OnChanPaymentDetails.tsx
web/src/features/transact/Payments/newPayment/newPayments.module.scss

* Feature: Create new invoice
Fixes https://github.com/lncapital/torq/issues/107

Add new invoice page

---

database/migrations/000042_add_node_name_column_to_local_node.up.psql
database/migrations/000043_populate_name_in_local_node.up.psql
internal/channels/handlers.go
internal/settings/database.go
internal/settings/node_connection_details.go
internal/settings/routes.go
web/src/apiTypes.ts
web/src/features/channels/ChannelsDataWrapper.tsx
web/src/features/channels/ChannelsSlice.tsx
web/src/features/channels/updateChannel/UpdateChannelModal.tsx
web/src/features/settings/NodeSettings.module.scss
web/src/features/settings/NodeSettings.tsx
web/src/features/transact/OnChain/newAddress/NewAddressModal.tsx
web/src/features/transact/Payments/newPayment/NewPaymentModal.tsx

Closes-> https://github.com/lncapital/torq/issues/154
- Added a name in the local_node table
- Updated existing names with Node + nodeID
- Updated the settings page to set or update the node name
- Fixed the Icon color issue with a successful update channel policy

Add default node name

---

database/migrations/000045_default_settings_timezone_to_utc.up.psql

related task -> https://github.com/lncapital/torq/issues/188
Fixes #188

set default timezone to UTC

---

web/src/apiSlice.ts
web/src/features/auth/LoginPage.tsx
web/src/types/api.ts

Fixes https://github.com/lncapital/torq/issues/144
When password is wrong
When api not reachable

Send error when wrong password

---

test/e2e/lnd/e2e_test.go
web/src/RequireAuth.tsx
web/src/features/auth/LoginPage.tsx
web/src/features/channel/DashboardPage.tsx
web/src/features/channel/channel-page.module.scss

Fixes #194 
When no nodes configured we display this pop-up

Add redirection to settings when no nodes

---

database/migrations/000046_corridors_and_tags.up.psql

Fix pubkey duplication error in the migration file.

Fix pubkey duplication error.

---

web/src/features/channels/openChannel/OpenChannelModal.tsx
web/src/features/channels/openChannel/openChannel.module.scss
web/src/features/forms/FormWrappers.tsx

Fixes the position issue for the labels "Private" and "Spend unconfirmed..."

Fix switch position

---

internal/channels/close_channel.go
internal/channels/handlers.go
web/public/locales/en.json
web/src/Router.tsx
web/src/apiTypes.ts
web/src/constants/routes.ts
web/src/features/channels/ChannelsPage.tsx
web/src/features/channels/closeChannel/CloseChannelModal.tsx
web/src/features/channels/closeChannel/closeChannel.module.scss
web/src/features/channels/openChannel/OpenChannelModal.tsx
web/src/features/channels/updateChannel/UpdateChannelModal.tsx
web/src/features/forms/Select.tsx

Fixes #105 
- Fix updateChannel policy channel selection
- Add close channel feature

close channel

---

web/public/locales/en.json
web/src/features/channels/updateChannel/UpdateChannelModal.tsx
web/src/features/channels/updateChannel/updateChannel.module.scss

fixes https://github.com/lncapital/internal-torq-roadmap/issues/1

fix update channel policy

---

internal/channels/database.go
internal/channels/handlers.go

- Get the correct remote policy

get correct remote policy

---

internal/channels/handlers.go
internal/channels/update_channel.go
internal/channels/update_channel_test.go

update transaction hash and index for policy update

---

pkg/lnd/forwards.go
pkg/lnd/forwards_test.go
pkg/lnd/invoices.go
pkg/lnd/payments.go
pkg/lnd/payments_test.go
pkg/lnd/transactions.go

Checking latest imported data did not take into account which node it was for

Check latest for node

---

internal/messages/handlers.go
internal/query_parser/cache_filter.go
web/public/locales/en.json
web/src/Router.tsx
web/src/components/buttons/Button.tsx
web/src/components/forms/chips/RadioChips.stories.tsx
web/src/components/forms/chips/RadioChips.tsx
web/src/components/forms/chips/radio_chips.module.scss
web/src/components/forms/form/Form.tsx
web/src/components/forms/forms.tsx
web/src/components/forms/input-colors.module.scss
web/src/components/forms/input/textInput.module.scss
web/src/components/forms/textArea/TextArea.tsx
web/src/constants/routes.ts
web/src/features/channels/openChannel/OpenChannelModal.tsx
web/src/features/navigation/MenuItem.tsx
web/src/features/navigation/Navigation.tsx
web/src/pages/messageVerificationPage/MessageVerificationModal.tsx
web/src/pages/messageVerificationPage/messageVerificationApi.ts
web/src/pages/messageVerificationPage/messageVerificationTypes.ts
web/src/pages/messageVerificationPage/message_verification.module.scss
web/src/pages/tags/tagsApi.ts

Sign and verify messages using the UI

Message verification

---

web/src/pages/WorkflowPage/workflowApi.ts

Fix empty node issue

---

internal/automation/triggerMonitor.go
internal/workflows/routes.go
internal/workflows/workflow.go
pkg/commons/constants.go
pkg/commons/events.go
web/public/locales/en.json
web/src/components/workflow/canvas/WorkflowCanvasStages.tsx
web/src/pages/WorkflowPage/workflowApi.ts
web/src/pages/WorkflowPage/workflowTypes.ts

Add manual trigger

---

cmd/torq/torq.go

Also fix formatting of some other options to be consistent with the rest.

Fix help for --db.password

---

web/src/features/navigation/nav.module.scss

Tidied up media query for mobile to ensure bottom navigation is not hidden by ios url toolbar

---

cmd/torq/torq.go

Fixes https://github.com/lncapital/internal-torq-roadmap/issues/143

Enable streams by default when Torq is bootstrapped with connection details.

---

web/src/components/workflow/links/WorkflowLinks.tsx
web/src/components/workflow/links/workflow_link.module.scss
web/src/components/workflow/nodeWrapper/NodeConnector.tsx
web/src/components/workflow/nodeWrapper/workflow_nodes.module.scss
web/src/pages/WorkflowPage/WorkflowSlice.ts
web/src/store/store.ts

Added new visuals to node connector to allow the user to preview the dragged line

Added preview line to dragged node

---

web/src/features/settings/SettingsPage.tsx
web/src/features/settings/settings.module.css

Adding the Torq version and Commit to the SettingsPage as
footer.
Fixes lncapital/internal-torq-roadmap#119

frontend: adding torq version footer.

---

cmd/torq/torq.go
internal/workflows/trigger.go
pkg/lnd/lightningCommunication.go

- backend main: adding loglevels
- backend workflow: adding more log messages
- lnd: fix small log bug and change log message

introduce debug level

---

web/src/features/channels/openChannel/OpenChannelModal.tsx

Fixes https://github.com/lncapital/internal-torq-roadmap/issues/161

fixes user is being able to select node when opening a channel

---

database/migrations/000080_workflow_example_tag_new.up.psql
database/migrations/000081_workflow_example_rebalance.up.psql
database/migrations/000082_workflow_example_autofee.up.psql
web/src/components/workflow/nodes/tags/RemoveTagNode.tsx

Corrected interval trigger type and minor changes to the workflow filters.

Changes example workflow migrations

---

web/src/features/transact/newAddress/NewAddressModal.tsx
web/src/features/transact/newAddress/newAddressTypes.ts

Fixed errors to allow addresses to be created

522 adding new address does not work

---

web/src/features/transact/NewPayment/NewPaymentModal.tsx

Refactored code to progress to the next step automatically only if a payment type matches

Fixed payment modal jumping to blank step

---

web/src/features/transact/NewPayment/InvoicePaymentResponse.tsx
web/src/features/transact/NewPayment/NewPaymentModal.tsx
web/src/features/transact/Payments/paymentTypes.ts

Fixes https://github.com/lncapital/torq/issues/525

Handle new server error format on payments

---

internal/query_parser/custom_operators.go
internal/views/views.go
internal/workflows/processFilter.go
web/src/features/sidebar/sections/filter/FilterRow.tsx

Fixes https://github.com/lncapital/torq/issues/469
NB! We still need to fix the filtering of Arrays and Enums in the processFilter.go file used in the automations!

Fixed enums for payments, invoices and on-chain transactions tables.

---

docker/example-docker-compose.yml

Fixes https://github.com/lncapital/internal-torq-roadmap/issues/204

add restart: always to example-docker-compose.yml

---

web/src/features/navigation/nav.module.scss
web/src/features/timeIntervalSelect/interval_select.scss

Fixes: https://github.com/lncapital/internal-torq-roadmap/issues/196
Fixes: https://github.com/lncapital/internal-torq-roadmap/issues/109

Fixes horizontal scroll bar in nav menu and z-index issue on date-range-container

---

web/public/locales/en.json
web/src/features/channels/openChannel/OpenChannelModal.tsx
web/src/features/channels/updateChannel/UpdateChannelModal.tsx

Fixes: https://github.com/lncapital/internal-torq-roadmap/issues/200

Updated open and update channel modals text

---

database/migrations/000084_invoices_page.up.psql
internal/invoices/invoices.go
internal/lnd/invoices.go

Fixes: https://github.com/lncapital/internal-torq-roadmap/issues/148

Invoices page performance problem.

---

internal/lnd/channelBalanceCache.go

referencing: https://github.com/lncapital/internal-torq-roadmap/issues/203

Extra logging for strange channel balance behaviour.

---

cmd/torq/internal/amboss_ping/server.go
cmd/torq/internal/vector_ping/server.go
cmd/torq/torq.go
go.mod
internal/automation/maintenance.go
internal/automation/triggerMonitor.go
internal/cache/services.go
internal/communications/notifier.go
internal/lnd/channelBalanceCache.go
internal/lnd/forwards.go
internal/lnd/payments.go
internal/workflows/rebalance.go
virtual_network/virtual_network.go

Fixes: https://github.com/lncapital/internal-torq-roadmap/issues/221
should fix resource leak

Updated Tickers to not use dependency and to stop

---

database/migrations/000087_delete_workflow_logs.up.psql
internal/automation/maintenance.go

Fixes: https://github.com/lncapital/internal-torq-roadmap/issues/225

Workflow logs cleanup process

---

web/src/components/summary/summaryCard/SummaryCard.tsx
web/src/components/summary/summaryCard/summary-card.module.scss
web/src/features/dashboard/DashboardPage.tsx
web/src/features/dashboard/dashboard-page.module.scss

Fixes: https://github.com/lncapital/internal-torq-roadmap/issues/198
Fixes: https://github.com/lncapital/internal-torq-roadmap/issues/218

Dashboard enhancements

---

web/src/features/peers/peersCellRenderer.tsx

fixes https://github.com/lncapital/internal-torq-roadmap/issues/237

fixes crashing peers column edits

---

cmd/torq/internal/subscribe/server.go
internal/cache/nodes.go
internal/channels/close_channel_test.go
internal/communications/notifier.go
internal/communications/telegram.go
internal/core/constants.go
internal/core/functions.go
internal/lightning/communication.go
internal/lnd/channelBalanceCache.go
internal/lnd/channel_events.go
internal/lnd/channel_events_test.go
internal/lnd/channelgraph.go
internal/lnd/channelgraph_test.go
internal/lnd/communication.go
internal/lnd/forwards_test.go
internal/lnd/invoices.go
internal/lnd/payments_test.go
internal/lnd/peer_events.go
internal/lnd/transactions_test.go
internal/nodes/database.go
internal/peers/database.go
internal/settings/database.go
internal/settings/routes.go

https://github.com/lncapital/internal-torq-roadmap/issues/232

Import peers aliases

---

internal/core/functions.go
internal/lnd/channelBalanceCache.go

https://github.com/lncapital/internal-torq-roadmap/issues/203

Channel capacity mismatch using existing cache as fallback.

---

web/src/features/transact/Invoices/invoiceDefaults.ts

Cleaning this minor issue
https://github.com/lncapital/torq/issues/452

Set default sort order to creationDate

---

internal/channels/handlers.go
internal/views/views.go
web/public/locales/en.json
web/src/features/channels/channelsCellRenderer.tsx
web/src/features/channels/channelsColumns.generated.ts
web/src/features/channels/channelsTypes.ts

Fix: do not display mempoolspace/amboss/1ml links if channel is private
Added: Private column to open channels

Fix: do not display mempoolspace/amboss/1ml if channel is private

---

web/src/features/settings/NodeSettings.tsx
web/src/features/settings/SettingsPage.tsx

Fixes: https://github.com/lncapital/torq/issues/603

Clear api cache when changing major things

---

internal/channel_history/handlers.go
internal/flow/handlers.go
web/src/features/channel/ChannelPage.tsx
web/src/features/channel/ForwardsSummary.tsx

The inspect pages used to show all channels for a channel id of 1.

forwards summary and inspect now using "all" instead of "1"

---

internal/settings/routes.go
web/src/App.tsx
web/src/components/workflow/canvas/WorkflowCanvas.tsx
web/src/components/workflow/nodeWrapper/NodeConnector.tsx
web/src/components/workflow/nodeWrapper/WorkflowNodeWrapper.tsx
web/src/utils/drag.ts

Polyfill for Firefox. Removed blank image as the frame of it was visible on ff. Couldn't see a difference on chrome.

Firefox drag and drop

---

internal/lnd/peer_events.go

Fixes: https://github.com/lncapital/internal-torq-roadmap/issues/244

Improve importing Peer status when Torq starts to sync the disconnected / connected state

---

internal/peers/database.go
internal/views/routes.go
internal/views/views.go
web/src/components/table/cells/peersCell/PeersAliasCell.tsx
web/src/features/peers/PeersPage.tsx
web/src/features/peers/peerUpdateModal.tsx
web/src/features/peers/peersColumns.generated.ts
web/src/features/peers/peersDefaults.ts
web/src/features/peers/peersTypes.ts
web/src/features/sidebar/sections/sort/SortSection.tsx
web/src/features/viewManagement/viewSlice.ts

Added DaysSinceLastConnected and DateLastConnected to peers to allow user to filter via the front end.

242 - Added DaysSinceLastConnected and DateLastConnected to peers page

---

web/src/components/buttons/Button.tsx
web/src/features/channels/channelsCellRenderer.tsx
web/src/features/channels/channelsDefaults.ts
web/src/features/viewManagement/ViewRow.tsx

fixes https://github.com/lncapital/internal-torq-roadmap/issues/256
fixes https://github.com/lncapital/internal-torq-roadmap/issues/254

Open channel views crashing the UI

---

web/src/features/channel/ForwardsSummary.tsx

Added TableControlSection to house TimeIntervalSelect and Refresh button for better UX

250 - move time interval and add refresh button

---

.gitignore
CONTRIBUTING.md
test/e2e/lnd/e2e_test.go
virtual_network/docker.go
virtual_network/virtual_network.go

You can now add alice and carol as well as bob as nodes.

Give access to alice and carol for multi node development

---

web/public/locales/en.json
web/src/components/forms/socket/Socket.tsx
web/src/components/workflow/nodeButtonWrapper/NodeButtonWrapper.tsx
web/src/components/workflow/nodeWrapper/NodeConnector.tsx
web/src/components/workflow/nodeWrapper/WorkflowNodeWrapper.tsx
web/src/components/workflow/nodeWrapper/workflow_nodes.module.scss

fixes https://github.com/lncapital/internal-torq-roadmap/issues/201

dropping workflow nodes on other nodes or sockets errors with a toast

---

web/src/components/forms/socket/Socket.tsx
web/src/components/forms/socket/socket_input.module.scss
web/src/components/workflow/canvas/WorkflowCanvas.tsx
web/src/components/workflow/links/WorkflowLinks.tsx
web/src/components/workflow/links/workflow_link.module.scss
web/src/components/workflow/nodeButtonWrapper/NodeButtonWrapper.tsx
web/src/components/workflow/nodeWrapper/NodeConnector.tsx
web/src/components/workflow/nodeWrapper/WorkflowNodeWrapper.tsx

* removes scaling of links in firefox
* places links on top of workflow nodes
* corrects position of connector drops and links

fixes various drag and drop visual bugs in workflows

---

README.md
cmd/torq/internal/torqsrv/server.go
cmd/torq/torq.go
docker/example-torq.conf

final item on: https://github.com/fort-nix/nix-bitcoin/pull/592

Add ability to set network interface.

---

web/public/locales/en.json
web/src/features/channel/ChannelPage.tsx

Moved time select interval to the left, action buttons to the right with a refresh button and tags to appear in a new row.

261 - Move time select interval
